# Funding options for No One Will Pay
# Replace with your actual funding URLs

# GitHub Sponsors
# github: [proofofputt]

# Open Collective
# open_collective: noonewillpay

# Bitcoin Donation Address
custom: ["https://noonewillpay.com/donate", "bitcoin:bc1q..."]
