name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas for improving the platform.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Another approach could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocks my use of the platform)
        - High (significantly improves experience)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Authentication & Security
        - Survey System
        - Referral Program
        - Marketplace
        - Charity Pool
        - Admin Dashboard
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        As a [user type], I want to [action] so that [benefit].

        Example:
        As a business partner, I want to see real-time redemption analytics
        so that I can understand customer engagement.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have technical suggestions, share them here
      placeholder: This could be implemented by...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Include any mockups, wireframes, or examples from other platforms
      placeholder: Paste images or links here

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided a clear use case
          required: true
